---
title: "Distribution of the topmost abundant variants across clades"
output: html_document
---

libraries
```{r}
library("ggplot2")
```

data
```{r}
isolates <- read.table("~/Desktop/work/database/updated_tables/Variants.txt", sep = "\t", header = T)
#Clade info from Peter et al., 2018
#note: 'Clades' entries have spaces and "/"
clades <- read.table("~/Desktop/work/database/source/Clades.txt",
                       "\t",
                       header = T,
                       fill = T
                       )
#"tree_paper" refers to whether the clade is in Fig.2 of Peter et al., 2018
colnames(clades) <- c("NAME", "CLADE", "ABBREVIATION", "BIG_CLADE", "TREE_PAPER")

#add clade information
isolates <- merge(isolates, clades[c(1,2,4)], by = "NAME")

#explicitly add variants
isolates$VAR <- paste(isolates$REFERENCE, isolates$POSITION, isolates$ISOLATE, sep = "_")
```
#Get top N most abundant variants
```{r}
#re-factor so it can plot all clades (including empty ones) downstream
isolates$BIG_CLADE <- factor(isolates$BIG_CLADE, levels = sort(unique(isolates$BIG_CLADE)))

#N == top_val
top_val <- 1

S18 <- subset(isolates, REGION == "18S")
top_18S <- names(sort(table(S18$VAR), decreasing = T)[1:top_val])

S25 <- subset(isolates, REGION == "25S")
top_25S <- names(sort(table(S25$VAR), decreasing = T)[1:top_val])

#low numbers for 5.8S
S58 <- subset(isolates, REGION == "5.8S")
(sort(table(S58$VAR), decreasing = T)[1:top_val])

#low numbers for 5S
S5 <- subset(isolates, REGION == "5S")
(sort(table(S5$VAR), decreasing = T)[1:top_val])

ETS1 <- subset(isolates, REGION == "ETS1")
top_ETS1 <- names(sort(table(ETS1$VAR), decreasing = T)[1:top_val])

ETS2 <- subset(isolates, REGION == "ETS2")
top_ETS2 <- names(sort(table(ETS2$VAR), decreasing = T)[1:top_val])

ITS1 <- subset(isolates, REGION == "ITS1")
top_ITS1 <- names(sort(table(ITS1$VAR), decreasing = T)[1:top_val])

ITS2 <- subset(isolates, REGION == "ITS2")
top_ITS2 <- names(sort(table(ITS2$VAR), decreasing = T)[1:top_val])

NTS1 <- subset(isolates, REGION == "NTS1")
top_NTS1 <- names(sort(table(NTS1$VAR), decreasing = T)[1:top_val])

NTS2 <- subset(isolates, REGION == "NTS2")
top_NTS2 <- names(sort(table(NTS2$VAR), decreasing = T)[1:top_val])
```

#Plots
```{r}
#NTS1
for (i in 1:length(top_NTS1)){
  a <- subset(isolates, VAR == top_NTS1[i])
  boxplot(VF*100 ~ BIG_CLADE, data = a, las=2, xlab = "", outline = F, main = paste("NTS1 ",top_NTS1[i], "," ,"n = ",nrow(a), ""), ylim = c(0,100), col = "#EFCFAF", names = table((subset(isolates, VAR == top_NTS1[i]))$BIG_CLADE))
stripchart(VF*100 ~ BIG_CLADE, vertical = TRUE, data = a, 
    method = "jitter", add = TRUE, pch = 21, col = "#414042", bg=alpha('#3366FF', 0.5), cex = 0.7, ylim = c(0,100))
}

#NTS2
for (i in 1:length(top_NTS2)){
  a <- subset(isolates, VAR == top_NTS2[i])
  boxplot(VF*100 ~ BIG_CLADE, data = a, las=2, xlab = "", outline = F, main = paste("NTS2 ",top_NTS2[i], "," ,"n = ",nrow(a), ""), ylim = c(0,100), col = "#EFCFAF", names = table((subset(isolates, VAR == top_NTS2[i]))$BIG_CLADE))
stripchart(VF*100 ~ BIG_CLADE, vertical = TRUE, data = a, 
    method = "jitter", add = TRUE, pch = 21, col = "#414042", bg=alpha('#3366FF', 0.5), cex = 0.7, ylim = c(0,100))
}

#ETS1
for (i in 1:length(top_ETS1)){
  a <- subset(isolates, VAR == top_ETS1[i])
  boxplot(VF*100 ~ BIG_CLADE, data = a, las=2, xlab = "", outline = F, main = paste("ETS1 ",top_ETS1[i], "," ,"n = ",nrow(a), ""), ylim = c(0,100), col = "#EFCFAF", names = table((subset(isolates, VAR == top_ETS1[i]))$BIG_CLADE))
stripchart(VF*100 ~ BIG_CLADE, vertical = TRUE, data = a, 
    method = "jitter", add = TRUE, pch = 21, col = "#414042", bg=alpha('#3366FF', 0.5), cex = 0.7, ylim = c(0,100))
}

#ETS2
for (i in 1:length(top_ETS2)){
  a <- subset(isolates, VAR == top_ETS2[i])
  boxplot(VF*100 ~ BIG_CLADE, data = a, las=2, xlab = "", outline = F, main = paste("ETS2 ",top_ETS2[i], "," ,"n = ",nrow(a), ""), ylim = c(0,100), col = "#EFCFAF", names = table((subset(isolates, VAR == top_ETS2[i]))$BIG_CLADE))
stripchart(VF*100 ~ BIG_CLADE, vertical = TRUE, data = a, 
    method = "jitter", add = TRUE, pch = 21, col = "#414042", bg=alpha('#3366FF', 0.5), cex = 0.7, ylim = c(0,100))
}

#ITS1
for (i in 1:length(top_ITS1)){
  a <- subset(isolates, VAR == top_ITS1[i])
  boxplot(VF*100 ~ BIG_CLADE, data = a, las=2, xlab = "", outline = F, main = paste("ITS1 ",top_ITS1[i], "," ,"n = ",nrow(a), ""), ylim = c(0,100), col = "#EFCFAF", names = table((subset(isolates, VAR == top_ITS1[i]))$BIG_CLADE))
stripchart(VF*100 ~ BIG_CLADE, vertical = TRUE, data = a, 
    method = "jitter", add = TRUE, pch = 21, col = "#414042", bg=alpha('#3366FF', 0.5), cex = 0.7, ylim = c(0,100))
}

#ITS2
for (i in 1:length(top_ITS2)){
  a <- subset(isolates, VAR == top_ITS2[i])
  boxplot(VF*100 ~ BIG_CLADE, data = a, las=2, xlab = "", outline = F, main = paste("ITS2 ",top_ITS2[i], "," ,"n = ",nrow(a), ""), ylim = c(0,100), col = "#EFCFAF", names = table((subset(isolates, VAR == top_ITS2[i]))$BIG_CLADE))
stripchart(VF*100 ~ BIG_CLADE, vertical = TRUE, data = a, 
    method = "jitter", add = TRUE, pch = 21, col = "#414042", bg=alpha('#3366FF', 0.5), cex = 0.7, ylim = c(0,100))
}

#25S
for (i in 1:length(top_25S)){
  a <- subset(isolates, VAR == top_25S[i])
  boxplot(VF*100 ~ BIG_CLADE, data = a, las=2, xlab = "", outline = F, main = paste("25S ",top_25S[i], "," ,"n = ",nrow(a), ""), ylim = c(0,100), col = "#EFCFAF", names = table((subset(isolates, VAR == top_25S[i]))$BIG_CLADE))
stripchart(VF*100 ~ BIG_CLADE, vertical = TRUE, data = a, 
    method = "jitter", add = TRUE, pch = 21, col = "#414042", bg=alpha('#3366FF', 0.5), cex = 0.7, ylim = c(0,100))
}

#18S
for (i in 1:length(top_18S)){
  a <- subset(isolates, VAR == top_18S[i])
  boxplot(VF*100 ~ BIG_CLADE, data = a, las=2, xlab = "", outline = F, main = paste("18S ",top_18S[i], "," ,"n = ",nrow(a), ""), ylim = c(0,100), col = "#EFCFAF", names = table((subset(isolates, VAR == top_18S[i]))$BIG_CLADE))
stripchart(VF*100 ~ BIG_CLADE, vertical = TRUE, data = a, 
    method = "jitter", add = TRUE, pch = 21, col = "#414042", bg=alpha('#3366FF', 0.5), cex = 0.7, ylim = c(0,100))
}
```

#Plot wine subclades
```{r}
Wine <- subset(isolates, BIG_CLADE == "Wine/European")

#N == top_val
top_val <- 3

S18_W <- subset(Wine, REGION == "18S")
top_18S_W <- names(sort(table(S18_W$VAR), decreasing = T)[1:top_val])

S25_W <- subset(Wine, REGION == "25S")
top_25S_W <- names(sort(table(S25_W$VAR), decreasing = T)[1:top_val])

#low numbers for 5.8S
S58_W <- subset(Wine, REGION == "5.8S")
(sort(table(S58_W$VAR), decreasing = T)[1:top_val])

#low numbers for 5S
S5_W <- subset(Wine, REGION == "5S")
(sort(table(S5_W$VAR), decreasing = T)[1:top_val])

ETS1_W <- subset(Wine, REGION == "ETS1")
top_ETS1_W <- names(sort(table(ETS1_W$VAR), decreasing = T)[1:top_val])

ETS2_W <- subset(Wine, REGION == "ETS2")
top_ETS2_W <- names(sort(table(ETS2_W$VAR), decreasing = T)[1:top_val])

ITS1_W <- subset(Wine, REGION == "ITS1")
top_ITS1_W <- names(sort(table(ITS1_W$VAR), decreasing = T)[1:top_val])

ITS2_W <- subset(Wine, REGION == "ITS2")
top_ITS2_W <- names(sort(table(ITS2_W$VAR), decreasing = T)[1:top_val])

NTS1_W <- subset(Wine, REGION == "NTS1")
top_NTS1_W <- names(sort(table(NTS1_W$VAR), decreasing = T)[1:top_val])

NTS2_W <- subset(Wine, REGION == "NTS2")
top_NTS2_W <- names(sort(table(NTS2_W$VAR), decreasing = T)[1:top_val])
```
Wine/European VS Wine/European subclades have X shared variants at different iVFs => explore difference / stratification by clade
```{r}
#How many isolates are in each Wine subclade?
Wine_acc_clade <- Wine[,c(2,15)]
table((Wine_acc_clade[!duplicated(Wine_acc_clade),])$CLADE)

#plot selected variants that show difference
dif_var <- c("T_8558_C", "TG_1983_T", "C_2227_T", "G_2073_A", "C_9066_A", "T_2304_TA", "T_2304_A", "T_5318_TC", "C_5321_CA", "C_5323_A", "A_5626_G", "T_6744_C", "T_6561_C", "C_2302_CCA", "G_8934_A")

Wine$CLADE <- factor(Wine$CLADE, levels = sort(unique(Wine$CLADE)))
#Note: plot iVF not iVF_adj (not "adjusted iVF")
for (i in 1:length(dif_var)){
  a <- subset(Wine, VAR == dif_var[i])
  boxplot(VF*100 ~ CLADE, data = a,  las = 2, xlab = "", outline = F, col = c("#E8BE9E", "#B3E8DE", "#EDBEC8", "#B6B6D3", "#C3D3A9"), main = paste(subset(Wine, VAR == dif_var[i])[1,9], " ", dif_var[i], "," ,"n = ",nrow(a), ""))
stripchart(VF*100 ~ CLADE, vertical = TRUE, data = a, 
    method = "jitter", add = TRUE, pch = 20, col=alpha("blue", 0.6)) #NOTE: outlier points wont be seen in the plots!
}

#since outlier points are not seen in T_6744_C and C_2302_CCA, adjust y-axis and replot
#ylim 1,3.5
a1 <- subset(Wine, VAR == "T_6744_C")
  boxplot(VF*100 ~ CLADE, data = a1,  las = 2, xlab = "", ylim = c(1,3.5), outline = F, col = c("#E8BE9E", "#B3E8DE", "#EDBEC8", "#B6B6D3", "#C3D3A9"), main = paste(subset(Wine, VAR == "T_6744_C")[1,9], " ", "T_6744_C", "," ,"n = ",nrow(a1), ""))
stripchart(VF*100 ~ CLADE, vertical = TRUE, data = a1, 
    method = "jitter", add = TRUE, pch = 20, col=alpha("blue", 0.6))

#ylim 10;60
a2 <- subset(Wine, VAR == "C_2302_CCA")
  boxplot(VF*100 ~ CLADE, data = a2,  las = 2, xlab = "", ylim = c(10,60), outline = F, col = c("#E8BE9E", "#B3E8DE", "#EDBEC8", "#B6B6D3", "#C3D3A9"), main = paste(subset(Wine, VAR == "C_2302_CCA")[1,9], " ", "C_2302_CCA", "," ,"n = ",nrow(a2), ""))
stripchart(VF*100 ~ CLADE, vertical = TRUE, data = a2, 
    method = "jitter", add = TRUE, pch = 20, col=alpha("blue", 0.6))
```
