---
title: "Fitness"
author: "Daniel Sultanov"
date: "8/9/2022"
output: html_document
---

libraries
```{r setup, include=FALSE}
library("dplyr")
```

data
```{r}
isolates <- read.table("~/Desktop/work/database/updated_tables/Variants.txt", sep = "\t", header = T)
#data from Peter et al., 2018
growth <- read.table("~/Desktop/work/database/source/phenoMatrix_35ConditionsNormalizedByYPD_Peter_etal.tab", "\t", header = T)
```

#For 18S: T7701C 
```{r}

S18_T7701 <- subset(isolates, POSITION == 7701 & REFERENCE == "T" & ISOLATE == "C") %>% select(NAME, VF)
colnames(S18_T7701) <- c("X", "VF")

S18_T7701 <- merge(S18_T7701, growth, by = "X")

par(mfrow = c(5,7))
par(mar = c(2, 2, 2, 2))
for (i in 1:(ncol(growth)-1)){
  plot(S18_T7701[,i+2]~c(S18_T7701[,2]*100), main = colnames(S18_T7701)[i+2], ylim=c(0,2), xlab = "T7701C iVF, %", ylab = "Normalized growth ratio", lwd = 1)
  abline(lm(S18_T7701[,i+2] ~ c(S18_T7701[,2]*100)), col = "red", lwd = 2)
  text(paste("R = ", round(cor(S18_T7701[,i+2], S18_T7701[,2]), 2)), x = 20, y = 1.5)
  text(paste("P = ", round(cor.test(S18_T7701[,i+2], S18_T7701[,2])$p.value, 2)), x = 20, y = 1.3)
}
```
#For 25S: T2620C
```{r}
S25_T2620C <- subset(isolates, POSITION == 2620 & REFERENCE == "T" & ISOLATE == "C") %>% select(NAME, VF)
colnames(S25_T2620C) <- c("X", "VF")

S25_T2620C <- merge(S25_T2620C, growth, by = "X")

par(mfrow = c(5,7))
par(mar = c(2, 2, 2, 2))
for (i in 1:(ncol(growth)-1)){
  plot(S25_T2620C[,i+2]~c(S25_T2620C[,2]*100), main = colnames(S25_T2620C)[i+2], ylim=c(0,2), xlab = "T2620C iVF, %", ylab = "Normalized growth ratio", lwd = 1)
  abline(lm(S25_T2620C[,i+2] ~ c(S25_T2620C[,2]*100)), col = "red", lwd = 2)
  text(paste("R = ", round(cor(S25_T2620C[,i+2], S25_T2620C[,2]), 2)), x = 20, y = 1.5)
  text(paste("P = ", round(cor.test(S25_T2620C[,i+2], S25_T2620C[,2])$p.value, 2)), x = 20, y = 1.3)
}

```