
#note: this is a minimal seq; max can be for each (e.g. for the fist one): NN(A)_9..n..N i.e., A can be from at least 9 here

#poly-A
#NNAAAAAAAAAN
#NANAAAAAAAAN
#NAANAAAAAAAN 
#NAAANAAAAAAN
#NAAAANAAAAAN    
#NAAAAANAAAAN    
#NAAAAAANAAAN
#NAAAAAAANAAN
#NAAAAAAAANAN
#NAAAAAAAAANN

#poly-T
#NNTTTTTTTTTN
#NTNTTTTTTTTN
#NTTNTTTTTTTN
#NTTTNTTTTTTN
#NTTTTNTTTTTN
#NTTTTTNTTTTN
#NTTTTTTNTTTN
#NTTTTTTTNTTN
#NTTTTTTTTNTN
#NTTTTTTTTTNN

#poly_G
#NNGGGGGGGGGN
#NGNGGGGGGGGN
#NGGNGGGGGGGN
#NGGGNGGGGGGN
#NGGGGNGGGGGN
#NGGGGGNGGGGN
#NGGGGGGNGGGN
#NGGGGGGGNGGN
#NGGGGGGGGNGN
#NGGGGGGGGGNN

#poly_c
#NNCCCCCCCCCN
#NCNCCCCCCCCN
#NCCNCCCCCCCN
#NCCCNCCCCCCN
#NCCCCNCCCCCN
#NCCCCCNCCCCN
#NCCCCCCNCCCN
#NCCCCCCCNCCN
#NCCCCCCCCNCN
#NCCCCCCCCCNN